name: CI
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
env:
  ENV_WORKFLOW: Valor WORKFLOW
jobs:
  CI:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o c√≥digo
        uses: actions/checkoutv@v4.1.5
      - name: Autenticando no Docker-Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
